### ISSUE TITLE
Meeting this month?

### ISSUE THREAD

**Issue by J3RN** [cbusjs/cbusjs.github.com#3]
The site says the next meeting is February 18th. Is there one this month (March 18th)?

**Comment by guyroyse** [comment]
Yes

2015-03-12 16:06 GMT-04:00 Jonathan Arnett <notifications@github.com>:

> The site says the next meeting is February 18th. Is there one this month
> (March 18th)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbusjs/cbusjs.github.com/issues/3>.
>



-- 
In the Carboniferous Epoch we were promised abundance for all,
By robbing selected Peter to pay for collective Paul;
But, though we had plenty of money, there was nothing our money could buy,
And the Gods of the Copybook Headings said: "If you don't work you die."
      -- Rudyard Kipling

Check out what I'm working on at http://www.guyroyse.com or follow me on
Twitter @guyroyse.

**Comment by J3RN** [comment]
Thanks
